apiVersion: v1
kind: Service
metadata:
  name: imageup-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 31111
    targetPort: 31111
  selector:
    app: imageup
